package modelo.pojo;
// Generated 15-mar-2017 16:17:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblAreaCuenta generated by hbm2java
 */
public class TblAreaCuenta  implements java.io.Serializable {


     private int idArea;
     private String codigoA;
     private String nombreA;
     private Set tblCuentaMadreCrs = new HashSet(0);

    public TblAreaCuenta() {
    }

	
    public TblAreaCuenta(int idArea) {
        this.idArea = idArea;
    }
    public TblAreaCuenta(int idArea, String codigoA, String nombreA, Set tblCuentaMadreCrs) {
       this.idArea = idArea;
       this.codigoA = codigoA;
       this.nombreA = nombreA;
       this.tblCuentaMadreCrs = tblCuentaMadreCrs;
    }
   
    public int getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(int idArea) {
        this.idArea = idArea;
    }
    public String getCodigoA() {
        return this.codigoA;
    }
    
    public void setCodigoA(String codigoA) {
        this.codigoA = codigoA;
    }
    public String getNombreA() {
        return this.nombreA;
    }
    
    public void setNombreA(String nombreA) {
        this.nombreA = nombreA;
    }
    public Set getTblCuentaMadreCrs() {
        return this.tblCuentaMadreCrs;
    }
    
    public void setTblCuentaMadreCrs(Set tblCuentaMadreCrs) {
        this.tblCuentaMadreCrs = tblCuentaMadreCrs;
    }




}


