package modelo.pojo;
// Generated 15-mar-2017 16:17:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblCuentaMadreCr generated by hbm2java
 */
public class TblCuentaMadreCr  implements java.io.Serializable {


     private int idMadreCr;
     private TblAreaCuenta tblAreaCuenta;
     private String codigomCr;
     private String nombreCrm;
     private Set tblCuentaHijaCrs = new HashSet(0);

    public TblCuentaMadreCr() {
    }

	
    public TblCuentaMadreCr(int idMadreCr, TblAreaCuenta tblAreaCuenta, String codigomCr, String nombreCrm) {
        this.idMadreCr = idMadreCr;
        this.tblAreaCuenta = tblAreaCuenta;
        this.codigomCr = codigomCr;
        this.nombreCrm = nombreCrm;
    }
    public TblCuentaMadreCr(int idMadreCr, TblAreaCuenta tblAreaCuenta, String codigomCr, String nombreCrm, Set tblCuentaHijaCrs) {
       this.idMadreCr = idMadreCr;
       this.tblAreaCuenta = tblAreaCuenta;
       this.codigomCr = codigomCr;
       this.nombreCrm = nombreCrm;
       this.tblCuentaHijaCrs = tblCuentaHijaCrs;
    }
   
    public int getIdMadreCr() {
        return this.idMadreCr;
    }
    
    public void setIdMadreCr(int idMadreCr) {
        this.idMadreCr = idMadreCr;
    }
    public TblAreaCuenta getTblAreaCuenta() {
        return this.tblAreaCuenta;
    }
    
    public void setTblAreaCuenta(TblAreaCuenta tblAreaCuenta) {
        this.tblAreaCuenta = tblAreaCuenta;
    }
    public String getCodigomCr() {
        return this.codigomCr;
    }
    
    public void setCodigomCr(String codigomCr) {
        this.codigomCr = codigomCr;
    }
    public String getNombreCrm() {
        return this.nombreCrm;
    }
    
    public void setNombreCrm(String nombreCrm) {
        this.nombreCrm = nombreCrm;
    }
    public Set getTblCuentaHijaCrs() {
        return this.tblCuentaHijaCrs;
    }
    
    public void setTblCuentaHijaCrs(Set tblCuentaHijaCrs) {
        this.tblCuentaHijaCrs = tblCuentaHijaCrs;
    }




}


