package modelo.pojo;
// Generated 15-mar-2017 16:17:44 by Hibernate Tools 4.3.1



/**
 * TblCuentaHijaCr generated by hbm2java
 */
public class TblCuentaHijaCr  implements java.io.Serializable {


     private int idHijaCr;
     private TblCuentaMadreCr tblCuentaMadreCr;
     private String codigoCr;
     private String nombreCr;

    public TblCuentaHijaCr() {
    }

    public TblCuentaHijaCr(int idHijaCr, TblCuentaMadreCr tblCuentaMadreCr, String codigoCr, String nombreCr) {
       this.idHijaCr = idHijaCr;
       this.tblCuentaMadreCr = tblCuentaMadreCr;
       this.codigoCr = codigoCr;
       this.nombreCr = nombreCr;
    }
   
    public int getIdHijaCr() {
        return this.idHijaCr;
    }
    
    public void setIdHijaCr(int idHijaCr) {
        this.idHijaCr = idHijaCr;
    }
    public TblCuentaMadreCr getTblCuentaMadreCr() {
        return this.tblCuentaMadreCr;
    }
    
    public void setTblCuentaMadreCr(TblCuentaMadreCr tblCuentaMadreCr) {
        this.tblCuentaMadreCr = tblCuentaMadreCr;
    }
    public String getCodigoCr() {
        return this.codigoCr;
    }
    
    public void setCodigoCr(String codigoCr) {
        this.codigoCr = codigoCr;
    }
    public String getNombreCr() {
        return this.nombreCr;
    }
    
    public void setNombreCr(String nombreCr) {
        this.nombreCr = nombreCr;
    }




}


