package modelo.pojo;
// Generated 15-mar-2017 16:17:44 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblEstudianteTutor generated by hbm2java
 */
public class TblEstudianteTutor  implements java.io.Serializable {


     private int id;
     private TblEstudianteMatricula tblEstudianteMatricula;
     private TblTutorMatricula tblTutorMatricula;
     private Integer idUsuarioCreo;
     private Date fechaCreacion;
     private Integer idModificaCrea;
     private Date fechaModificacion;

    public TblEstudianteTutor() {
    }

	
    public TblEstudianteTutor(int id) {
        this.id = id;
    }
    public TblEstudianteTutor(int id, TblEstudianteMatricula tblEstudianteMatricula, TblTutorMatricula tblTutorMatricula, Integer idUsuarioCreo, Date fechaCreacion, Integer idModificaCrea, Date fechaModificacion) {
       this.id = id;
       this.tblEstudianteMatricula = tblEstudianteMatricula;
       this.tblTutorMatricula = tblTutorMatricula;
       this.idUsuarioCreo = idUsuarioCreo;
       this.fechaCreacion = fechaCreacion;
       this.idModificaCrea = idModificaCrea;
       this.fechaModificacion = fechaModificacion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public TblEstudianteMatricula getTblEstudianteMatricula() {
        return this.tblEstudianteMatricula;
    }
    
    public void setTblEstudianteMatricula(TblEstudianteMatricula tblEstudianteMatricula) {
        this.tblEstudianteMatricula = tblEstudianteMatricula;
    }
    public TblTutorMatricula getTblTutorMatricula() {
        return this.tblTutorMatricula;
    }
    
    public void setTblTutorMatricula(TblTutorMatricula tblTutorMatricula) {
        this.tblTutorMatricula = tblTutorMatricula;
    }
    public Integer getIdUsuarioCreo() {
        return this.idUsuarioCreo;
    }
    
    public void setIdUsuarioCreo(Integer idUsuarioCreo) {
        this.idUsuarioCreo = idUsuarioCreo;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Integer getIdModificaCrea() {
        return this.idModificaCrea;
    }
    
    public void setIdModificaCrea(Integer idModificaCrea) {
        this.idModificaCrea = idModificaCrea;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


