package modelo.pojo;
// Generated 15-mar-2017 16:17:44 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblGrados generated by hbm2java
 */
public class TblGrados  implements java.io.Serializable {


     private int idGrado;
     private String grado;
     private Integer idUsuarioCreo;
     private Date fechaCreacion;
     private Integer idModificaCrea;
     private Date fechaModificacion;

    public TblGrados() {
    }

	
    public TblGrados(int idGrado) {
        this.idGrado = idGrado;
    }
    public TblGrados(int idGrado, String grado, Integer idUsuarioCreo, Date fechaCreacion, Integer idModificaCrea, Date fechaModificacion) {
       this.idGrado = idGrado;
       this.grado = grado;
       this.idUsuarioCreo = idUsuarioCreo;
       this.fechaCreacion = fechaCreacion;
       this.idModificaCrea = idModificaCrea;
       this.fechaModificacion = fechaModificacion;
    }
   
    public int getIdGrado() {
        return this.idGrado;
    }
    
    public void setIdGrado(int idGrado) {
        this.idGrado = idGrado;
    }
    public String getGrado() {
        return this.grado;
    }
    
    public void setGrado(String grado) {
        this.grado = grado;
    }
    public Integer getIdUsuarioCreo() {
        return this.idUsuarioCreo;
    }
    
    public void setIdUsuarioCreo(Integer idUsuarioCreo) {
        this.idUsuarioCreo = idUsuarioCreo;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Integer getIdModificaCrea() {
        return this.idModificaCrea;
    }
    
    public void setIdModificaCrea(Integer idModificaCrea) {
        this.idModificaCrea = idModificaCrea;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


