package modelo.pojo;
// Generated 15-mar-2017 16:17:44 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblInfoAdmision generated by hbm2java
 */
public class TblInfoAdmision  implements java.io.Serializable {


     private int idInfo;
     private TblEstudianteMatricula tblEstudianteMatricula;
     private String mes;
     private String anio;
     private String gradoActual;
     private Integer idGrado;
     private Integer idUsuarioCreo;
     private Date fechaCreacion;
     private Integer idModificaCrea;
     private Date fechaModificacion;

    public TblInfoAdmision() {
    }

	
    public TblInfoAdmision(int idInfo) {
        this.idInfo = idInfo;
    }
    public TblInfoAdmision(int idInfo, TblEstudianteMatricula tblEstudianteMatricula, String mes, String anio, String gradoActual, Integer idGrado, Integer idUsuarioCreo, Date fechaCreacion, Integer idModificaCrea, Date fechaModificacion) {
       this.idInfo = idInfo;
       this.tblEstudianteMatricula = tblEstudianteMatricula;
       this.mes = mes;
       this.anio = anio;
       this.gradoActual = gradoActual;
       this.idGrado = idGrado;
       this.idUsuarioCreo = idUsuarioCreo;
       this.fechaCreacion = fechaCreacion;
       this.idModificaCrea = idModificaCrea;
       this.fechaModificacion = fechaModificacion;
    }
   
    public int getIdInfo() {
        return this.idInfo;
    }
    
    public void setIdInfo(int idInfo) {
        this.idInfo = idInfo;
    }
    public TblEstudianteMatricula getTblEstudianteMatricula() {
        return this.tblEstudianteMatricula;
    }
    
    public void setTblEstudianteMatricula(TblEstudianteMatricula tblEstudianteMatricula) {
        this.tblEstudianteMatricula = tblEstudianteMatricula;
    }
    public String getMes() {
        return this.mes;
    }
    
    public void setMes(String mes) {
        this.mes = mes;
    }
    public String getAnio() {
        return this.anio;
    }
    
    public void setAnio(String anio) {
        this.anio = anio;
    }
    public String getGradoActual() {
        return this.gradoActual;
    }
    
    public void setGradoActual(String gradoActual) {
        this.gradoActual = gradoActual;
    }
    public Integer getIdGrado() {
        return this.idGrado;
    }
    
    public void setIdGrado(Integer idGrado) {
        this.idGrado = idGrado;
    }
    public Integer getIdUsuarioCreo() {
        return this.idUsuarioCreo;
    }
    
    public void setIdUsuarioCreo(Integer idUsuarioCreo) {
        this.idUsuarioCreo = idUsuarioCreo;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Integer getIdModificaCrea() {
        return this.idModificaCrea;
    }
    
    public void setIdModificaCrea(Integer idModificaCrea) {
        this.idModificaCrea = idModificaCrea;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


