package modelo.pojo;
// Generated 15-mar-2017 16:17:44 by Hibernate Tools 4.3.1



/**
 * TblMenuLabel generated by hbm2java
 */
public class TblMenuLabel  implements java.io.Serializable {


     private int idLabel;
     private String label;

    public TblMenuLabel() {
    }

    public TblMenuLabel(int idLabel, String label) {
       this.idLabel = idLabel;
       this.label = label;
    }
   
    public int getIdLabel() {
        return this.idLabel;
    }
    
    public void setIdLabel(int idLabel) {
        this.idLabel = idLabel;
    }
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }




}


