package modelo.pojo;
// Generated 15-mar-2017 16:17:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblMenu generated by hbm2java
 */
public class TblMenu  implements java.io.Serializable {


     private int idMenu;
     private String menu;
     private String pseudo;
     private String url;
     private Integer idLabel;
     private Set tblPerfilMenuses = new HashSet(0);
     private Set tblOpcioneses = new HashSet(0);
     private Set tblPermisosNavegacions = new HashSet(0);

    public TblMenu() {
    }

	
    public TblMenu(int idMenu, String menu, String pseudo, String url) {
        this.idMenu = idMenu;
        this.menu = menu;
        this.pseudo = pseudo;
        this.url = url;
    }
    public TblMenu(int idMenu, String menu, String pseudo, String url, Integer idLabel, Set tblPerfilMenuses, Set tblOpcioneses, Set tblPermisosNavegacions) {
       this.idMenu = idMenu;
       this.menu = menu;
       this.pseudo = pseudo;
       this.url = url;
       this.idLabel = idLabel;
       this.tblPerfilMenuses = tblPerfilMenuses;
       this.tblOpcioneses = tblOpcioneses;
       this.tblPermisosNavegacions = tblPermisosNavegacions;
    }
   
    public int getIdMenu() {
        return this.idMenu;
    }
    
    public void setIdMenu(int idMenu) {
        this.idMenu = idMenu;
    }
    public String getMenu() {
        return this.menu;
    }
    
    public void setMenu(String menu) {
        this.menu = menu;
    }
    public String getPseudo() {
        return this.pseudo;
    }
    
    public void setPseudo(String pseudo) {
        this.pseudo = pseudo;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Integer getIdLabel() {
        return this.idLabel;
    }
    
    public void setIdLabel(Integer idLabel) {
        this.idLabel = idLabel;
    }
    public Set getTblPerfilMenuses() {
        return this.tblPerfilMenuses;
    }
    
    public void setTblPerfilMenuses(Set tblPerfilMenuses) {
        this.tblPerfilMenuses = tblPerfilMenuses;
    }
    public Set getTblOpcioneses() {
        return this.tblOpcioneses;
    }
    
    public void setTblOpcioneses(Set tblOpcioneses) {
        this.tblOpcioneses = tblOpcioneses;
    }
    public Set getTblPermisosNavegacions() {
        return this.tblPermisosNavegacions;
    }
    
    public void setTblPermisosNavegacions(Set tblPermisosNavegacions) {
        this.tblPermisosNavegacions = tblPermisosNavegacions;
    }




}


