package modelo.pojo;
// Generated 15-mar-2017 16:17:44 by Hibernate Tools 4.3.1



/**
 * TblNacionalidad generated by hbm2java
 */
public class TblNacionalidad  implements java.io.Serializable {


     private int idNacionalidad;
     private String nacion;

    public TblNacionalidad() {
    }

	
    public TblNacionalidad(int idNacionalidad) {
        this.idNacionalidad = idNacionalidad;
    }
    public TblNacionalidad(int idNacionalidad, String nacion) {
       this.idNacionalidad = idNacionalidad;
       this.nacion = nacion;
    }
   
    public int getIdNacionalidad() {
        return this.idNacionalidad;
    }
    
    public void setIdNacionalidad(int idNacionalidad) {
        this.idNacionalidad = idNacionalidad;
    }
    public String getNacion() {
        return this.nacion;
    }
    
    public void setNacion(String nacion) {
        this.nacion = nacion;
    }




}


