package modelo.pojo;
// Generated 15-mar-2017 16:17:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblOpciones generated by hbm2java
 */
public class TblOpciones  implements java.io.Serializable {


     private int idOpcion;
     private TblMenu tblMenu;
     private String opcion;
     private String pseudo;
     private String url;
     private Set tblSubOpcioneses = new HashSet(0);
     private Set tblPerfilOpcioneses = new HashSet(0);

    public TblOpciones() {
    }

	
    public TblOpciones(int idOpcion, TblMenu tblMenu, String opcion, String pseudo, String url) {
        this.idOpcion = idOpcion;
        this.tblMenu = tblMenu;
        this.opcion = opcion;
        this.pseudo = pseudo;
        this.url = url;
    }
    public TblOpciones(int idOpcion, TblMenu tblMenu, String opcion, String pseudo, String url, Set tblSubOpcioneses, Set tblPerfilOpcioneses) {
       this.idOpcion = idOpcion;
       this.tblMenu = tblMenu;
       this.opcion = opcion;
       this.pseudo = pseudo;
       this.url = url;
       this.tblSubOpcioneses = tblSubOpcioneses;
       this.tblPerfilOpcioneses = tblPerfilOpcioneses;
    }
   
    public int getIdOpcion() {
        return this.idOpcion;
    }
    
    public void setIdOpcion(int idOpcion) {
        this.idOpcion = idOpcion;
    }
    public TblMenu getTblMenu() {
        return this.tblMenu;
    }
    
    public void setTblMenu(TblMenu tblMenu) {
        this.tblMenu = tblMenu;
    }
    public String getOpcion() {
        return this.opcion;
    }
    
    public void setOpcion(String opcion) {
        this.opcion = opcion;
    }
    public String getPseudo() {
        return this.pseudo;
    }
    
    public void setPseudo(String pseudo) {
        this.pseudo = pseudo;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Set getTblSubOpcioneses() {
        return this.tblSubOpcioneses;
    }
    
    public void setTblSubOpcioneses(Set tblSubOpcioneses) {
        this.tblSubOpcioneses = tblSubOpcioneses;
    }
    public Set getTblPerfilOpcioneses() {
        return this.tblPerfilOpcioneses;
    }
    
    public void setTblPerfilOpcioneses(Set tblPerfilOpcioneses) {
        this.tblPerfilOpcioneses = tblPerfilOpcioneses;
    }




}


