package modelo.pojo;
// Generated 15-mar-2017 16:17:44 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblOcupaciones generated by hbm2java
 */
public class TblOcupaciones  implements java.io.Serializable {


     private int idOcupacion;
     private String ocupacion;
     private Integer idUsuarioCreo;
     private Date fechaCreacion;
     private Integer idModificaCrea;
     private Date fechaModificacion;

    public TblOcupaciones() {
    }

	
    public TblOcupaciones(int idOcupacion) {
        this.idOcupacion = idOcupacion;
    }
    public TblOcupaciones(int idOcupacion, String ocupacion, Integer idUsuarioCreo, Date fechaCreacion, Integer idModificaCrea, Date fechaModificacion) {
       this.idOcupacion = idOcupacion;
       this.ocupacion = ocupacion;
       this.idUsuarioCreo = idUsuarioCreo;
       this.fechaCreacion = fechaCreacion;
       this.idModificaCrea = idModificaCrea;
       this.fechaModificacion = fechaModificacion;
    }
   
    public int getIdOcupacion() {
        return this.idOcupacion;
    }
    
    public void setIdOcupacion(int idOcupacion) {
        this.idOcupacion = idOcupacion;
    }
    public String getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }
    public Integer getIdUsuarioCreo() {
        return this.idUsuarioCreo;
    }
    
    public void setIdUsuarioCreo(Integer idUsuarioCreo) {
        this.idUsuarioCreo = idUsuarioCreo;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Integer getIdModificaCrea() {
        return this.idModificaCrea;
    }
    
    public void setIdModificaCrea(Integer idModificaCrea) {
        this.idModificaCrea = idModificaCrea;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


