package modelo.pojo;
// Generated 15-mar-2017 16:17:44 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblPerfilNavegacion generated by hbm2java
 */
public class TblPerfilNavegacion  implements java.io.Serializable {


     private int id;
     private TblPerfil tblPerfil;
     private TblPermisosNavegacion tblPermisosNavegacion;
     private int idUsuarioCreo;
     private Date fechaCreacion;
     private int idUsuarioModifica;
     private Date fechaModificacion;

    public TblPerfilNavegacion() {
    }

	
    public TblPerfilNavegacion(int id, TblPerfil tblPerfil, TblPermisosNavegacion tblPermisosNavegacion, int idUsuarioCreo, int idUsuarioModifica) {
        this.id = id;
        this.tblPerfil = tblPerfil;
        this.tblPermisosNavegacion = tblPermisosNavegacion;
        this.idUsuarioCreo = idUsuarioCreo;
        this.idUsuarioModifica = idUsuarioModifica;
    }
    public TblPerfilNavegacion(int id, TblPerfil tblPerfil, TblPermisosNavegacion tblPermisosNavegacion, int idUsuarioCreo, Date fechaCreacion, int idUsuarioModifica, Date fechaModificacion) {
       this.id = id;
       this.tblPerfil = tblPerfil;
       this.tblPermisosNavegacion = tblPermisosNavegacion;
       this.idUsuarioCreo = idUsuarioCreo;
       this.fechaCreacion = fechaCreacion;
       this.idUsuarioModifica = idUsuarioModifica;
       this.fechaModificacion = fechaModificacion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public TblPerfil getTblPerfil() {
        return this.tblPerfil;
    }
    
    public void setTblPerfil(TblPerfil tblPerfil) {
        this.tblPerfil = tblPerfil;
    }
    public TblPermisosNavegacion getTblPermisosNavegacion() {
        return this.tblPermisosNavegacion;
    }
    
    public void setTblPermisosNavegacion(TblPermisosNavegacion tblPermisosNavegacion) {
        this.tblPermisosNavegacion = tblPermisosNavegacion;
    }
    public int getIdUsuarioCreo() {
        return this.idUsuarioCreo;
    }
    
    public void setIdUsuarioCreo(int idUsuarioCreo) {
        this.idUsuarioCreo = idUsuarioCreo;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public int getIdUsuarioModifica() {
        return this.idUsuarioModifica;
    }
    
    public void setIdUsuarioModifica(int idUsuarioModifica) {
        this.idUsuarioModifica = idUsuarioModifica;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


