package modelo.pojo;
// Generated 15-mar-2017 16:17:44 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblPerfil generated by hbm2java
 */
public class TblPerfil  implements java.io.Serializable {


     private int idperfil;
     private String nombre;
     private String descripcion;
     private int idUsuarioCreo;
     private Date fechaCreacion;
     private int idUsuarioModifica;
     private Date fechaModificacion;
     private Set tblPerfilMenuses = new HashSet(0);
     private Set tblPerfilOpcioneses = new HashSet(0);
     private Set tblUsuarioPerfils = new HashSet(0);
     private Set tblPerfilNavegacions = new HashSet(0);
     private Set tblPerfilSubopcioneses = new HashSet(0);

    public TblPerfil() {
    }

	
    public TblPerfil(int idperfil, String nombre, String descripcion, int idUsuarioCreo, int idUsuarioModifica) {
        this.idperfil = idperfil;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.idUsuarioCreo = idUsuarioCreo;
        this.idUsuarioModifica = idUsuarioModifica;
    }
    public TblPerfil(int idperfil, String nombre, String descripcion, int idUsuarioCreo, Date fechaCreacion, int idUsuarioModifica, Date fechaModificacion, Set tblPerfilMenuses, Set tblPerfilOpcioneses, Set tblUsuarioPerfils, Set tblPerfilNavegacions, Set tblPerfilSubopcioneses) {
       this.idperfil = idperfil;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.idUsuarioCreo = idUsuarioCreo;
       this.fechaCreacion = fechaCreacion;
       this.idUsuarioModifica = idUsuarioModifica;
       this.fechaModificacion = fechaModificacion;
       this.tblPerfilMenuses = tblPerfilMenuses;
       this.tblPerfilOpcioneses = tblPerfilOpcioneses;
       this.tblUsuarioPerfils = tblUsuarioPerfils;
       this.tblPerfilNavegacions = tblPerfilNavegacions;
       this.tblPerfilSubopcioneses = tblPerfilSubopcioneses;
    }
   
    public int getIdperfil() {
        return this.idperfil;
    }
    
    public void setIdperfil(int idperfil) {
        this.idperfil = idperfil;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getIdUsuarioCreo() {
        return this.idUsuarioCreo;
    }
    
    public void setIdUsuarioCreo(int idUsuarioCreo) {
        this.idUsuarioCreo = idUsuarioCreo;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public int getIdUsuarioModifica() {
        return this.idUsuarioModifica;
    }
    
    public void setIdUsuarioModifica(int idUsuarioModifica) {
        this.idUsuarioModifica = idUsuarioModifica;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getTblPerfilMenuses() {
        return this.tblPerfilMenuses;
    }
    
    public void setTblPerfilMenuses(Set tblPerfilMenuses) {
        this.tblPerfilMenuses = tblPerfilMenuses;
    }
    public Set getTblPerfilOpcioneses() {
        return this.tblPerfilOpcioneses;
    }
    
    public void setTblPerfilOpcioneses(Set tblPerfilOpcioneses) {
        this.tblPerfilOpcioneses = tblPerfilOpcioneses;
    }
    public Set getTblUsuarioPerfils() {
        return this.tblUsuarioPerfils;
    }
    
    public void setTblUsuarioPerfils(Set tblUsuarioPerfils) {
        this.tblUsuarioPerfils = tblUsuarioPerfils;
    }
    public Set getTblPerfilNavegacions() {
        return this.tblPerfilNavegacions;
    }
    
    public void setTblPerfilNavegacions(Set tblPerfilNavegacions) {
        this.tblPerfilNavegacions = tblPerfilNavegacions;
    }
    public Set getTblPerfilSubopcioneses() {
        return this.tblPerfilSubopcioneses;
    }
    
    public void setTblPerfilSubopcioneses(Set tblPerfilSubopcioneses) {
        this.tblPerfilSubopcioneses = tblPerfilSubopcioneses;
    }




}


