package modelo.pojo;
// Generated 15-mar-2017 16:17:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblSociedad generated by hbm2java
 */
public class TblSociedad  implements java.io.Serializable {


     private int idSociedad;
     private String sociedad;
     private String logo;
     private Set tblUsuarioSociedads = new HashSet(0);

    public TblSociedad() {
    }

	
    public TblSociedad(int idSociedad) {
        this.idSociedad = idSociedad;
    }
    public TblSociedad(int idSociedad, String sociedad, String logo, Set tblUsuarioSociedads) {
       this.idSociedad = idSociedad;
       this.sociedad = sociedad;
       this.logo = logo;
       this.tblUsuarioSociedads = tblUsuarioSociedads;
    }
   
    public int getIdSociedad() {
        return this.idSociedad;
    }
    
    public void setIdSociedad(int idSociedad) {
        this.idSociedad = idSociedad;
    }
    public String getSociedad() {
        return this.sociedad;
    }
    
    public void setSociedad(String sociedad) {
        this.sociedad = sociedad;
    }
    public String getLogo() {
        return this.logo;
    }
    
    public void setLogo(String logo) {
        this.logo = logo;
    }
    public Set getTblUsuarioSociedads() {
        return this.tblUsuarioSociedads;
    }
    
    public void setTblUsuarioSociedads(Set tblUsuarioSociedads) {
        this.tblUsuarioSociedads = tblUsuarioSociedads;
    }




}


