package modelo.pojo;
// Generated 15-mar-2017 16:17:44 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblTutorMatricula generated by hbm2java
 */
public class TblTutorMatricula  implements java.io.Serializable {


     private int idTutor;
     private String nombre;
     private Integer idOcupacion;
     private String nombreEmpresa;
     private String direccionCasa;
     private String ciudadRes;
     private Integer idPaisRes;
     private String telefonoCelular;
     private String direccionTrabajo;
     private String ciudadTrabajo;
     private Integer idPaisTra;
     private String telefonoTrabajo;
     private String telefonoCasa;
     private String noIdentidad;
     private String noPasaporte;
     private String correo;
     private Integer idUsuarioCreo;
     private Date fechaCreacion;
     private Integer idModificaCrea;
     private Date fechaModificacion;
     private Set tblEstudianteTutors = new HashSet(0);

    public TblTutorMatricula() {
    }

	
    public TblTutorMatricula(int idTutor) {
        this.idTutor = idTutor;
    }
    public TblTutorMatricula(int idTutor, String nombre, Integer idOcupacion, String nombreEmpresa, String direccionCasa, String ciudadRes, Integer idPaisRes, String telefonoCelular, String direccionTrabajo, String ciudadTrabajo, Integer idPaisTra, String telefonoTrabajo, String telefonoCasa, String noIdentidad, String noPasaporte, String correo, Integer idUsuarioCreo, Date fechaCreacion, Integer idModificaCrea, Date fechaModificacion, Set tblEstudianteTutors) {
       this.idTutor = idTutor;
       this.nombre = nombre;
       this.idOcupacion = idOcupacion;
       this.nombreEmpresa = nombreEmpresa;
       this.direccionCasa = direccionCasa;
       this.ciudadRes = ciudadRes;
       this.idPaisRes = idPaisRes;
       this.telefonoCelular = telefonoCelular;
       this.direccionTrabajo = direccionTrabajo;
       this.ciudadTrabajo = ciudadTrabajo;
       this.idPaisTra = idPaisTra;
       this.telefonoTrabajo = telefonoTrabajo;
       this.telefonoCasa = telefonoCasa;
       this.noIdentidad = noIdentidad;
       this.noPasaporte = noPasaporte;
       this.correo = correo;
       this.idUsuarioCreo = idUsuarioCreo;
       this.fechaCreacion = fechaCreacion;
       this.idModificaCrea = idModificaCrea;
       this.fechaModificacion = fechaModificacion;
       this.tblEstudianteTutors = tblEstudianteTutors;
    }
   
    public int getIdTutor() {
        return this.idTutor;
    }
    
    public void setIdTutor(int idTutor) {
        this.idTutor = idTutor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getIdOcupacion() {
        return this.idOcupacion;
    }
    
    public void setIdOcupacion(Integer idOcupacion) {
        this.idOcupacion = idOcupacion;
    }
    public String getNombreEmpresa() {
        return this.nombreEmpresa;
    }
    
    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }
    public String getDireccionCasa() {
        return this.direccionCasa;
    }
    
    public void setDireccionCasa(String direccionCasa) {
        this.direccionCasa = direccionCasa;
    }
    public String getCiudadRes() {
        return this.ciudadRes;
    }
    
    public void setCiudadRes(String ciudadRes) {
        this.ciudadRes = ciudadRes;
    }
    public Integer getIdPaisRes() {
        return this.idPaisRes;
    }
    
    public void setIdPaisRes(Integer idPaisRes) {
        this.idPaisRes = idPaisRes;
    }
    public String getTelefonoCelular() {
        return this.telefonoCelular;
    }
    
    public void setTelefonoCelular(String telefonoCelular) {
        this.telefonoCelular = telefonoCelular;
    }
    public String getDireccionTrabajo() {
        return this.direccionTrabajo;
    }
    
    public void setDireccionTrabajo(String direccionTrabajo) {
        this.direccionTrabajo = direccionTrabajo;
    }
    public String getCiudadTrabajo() {
        return this.ciudadTrabajo;
    }
    
    public void setCiudadTrabajo(String ciudadTrabajo) {
        this.ciudadTrabajo = ciudadTrabajo;
    }
    public Integer getIdPaisTra() {
        return this.idPaisTra;
    }
    
    public void setIdPaisTra(Integer idPaisTra) {
        this.idPaisTra = idPaisTra;
    }
    public String getTelefonoTrabajo() {
        return this.telefonoTrabajo;
    }
    
    public void setTelefonoTrabajo(String telefonoTrabajo) {
        this.telefonoTrabajo = telefonoTrabajo;
    }
    public String getTelefonoCasa() {
        return this.telefonoCasa;
    }
    
    public void setTelefonoCasa(String telefonoCasa) {
        this.telefonoCasa = telefonoCasa;
    }
    public String getNoIdentidad() {
        return this.noIdentidad;
    }
    
    public void setNoIdentidad(String noIdentidad) {
        this.noIdentidad = noIdentidad;
    }
    public String getNoPasaporte() {
        return this.noPasaporte;
    }
    
    public void setNoPasaporte(String noPasaporte) {
        this.noPasaporte = noPasaporte;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Integer getIdUsuarioCreo() {
        return this.idUsuarioCreo;
    }
    
    public void setIdUsuarioCreo(Integer idUsuarioCreo) {
        this.idUsuarioCreo = idUsuarioCreo;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Integer getIdModificaCrea() {
        return this.idModificaCrea;
    }
    
    public void setIdModificaCrea(Integer idModificaCrea) {
        this.idModificaCrea = idModificaCrea;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getTblEstudianteTutors() {
        return this.tblEstudianteTutors;
    }
    
    public void setTblEstudianteTutors(Set tblEstudianteTutors) {
        this.tblEstudianteTutors = tblEstudianteTutors;
    }




}


