package modelo.pojo;
// Generated 15-mar-2017 16:17:44 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblUsuario generated by hbm2java
 */
public class TblUsuario  implements java.io.Serializable {


     private int idUsuario;
     private TblUsuarioTipo tblUsuarioTipo;
     private String usuario;
     private String correo;
     private String pass;
     private String nombreCompleto;
     private Boolean estado;
     private Boolean confirmacion;
     private Integer idUsuarioCreo;
     private Date fechaCreacion;
     private Integer idModificaCrea;
     private Date fechaModificacion;
     private Set tblUsuarioSociedads = new HashSet(0);
     private Set tblUsuarioPerfils = new HashSet(0);

    public TblUsuario() {
    }

	
    public TblUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public TblUsuario(int idUsuario, TblUsuarioTipo tblUsuarioTipo, String usuario, String correo, String pass, String nombreCompleto, Boolean estado, Boolean confirmacion, Integer idUsuarioCreo, Date fechaCreacion, Integer idModificaCrea, Date fechaModificacion, Set tblUsuarioSociedads, Set tblUsuarioPerfils) {
       this.idUsuario = idUsuario;
       this.tblUsuarioTipo = tblUsuarioTipo;
       this.usuario = usuario;
       this.correo = correo;
       this.pass = pass;
       this.nombreCompleto = nombreCompleto;
       this.estado = estado;
       this.confirmacion = confirmacion;
       this.idUsuarioCreo = idUsuarioCreo;
       this.fechaCreacion = fechaCreacion;
       this.idModificaCrea = idModificaCrea;
       this.fechaModificacion = fechaModificacion;
       this.tblUsuarioSociedads = tblUsuarioSociedads;
       this.tblUsuarioPerfils = tblUsuarioPerfils;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public TblUsuarioTipo getTblUsuarioTipo() {
        return this.tblUsuarioTipo;
    }
    
    public void setTblUsuarioTipo(TblUsuarioTipo tblUsuarioTipo) {
        this.tblUsuarioTipo = tblUsuarioTipo;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }
    
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Boolean getConfirmacion() {
        return this.confirmacion;
    }
    
    public void setConfirmacion(Boolean confirmacion) {
        this.confirmacion = confirmacion;
    }
    public Integer getIdUsuarioCreo() {
        return this.idUsuarioCreo;
    }
    
    public void setIdUsuarioCreo(Integer idUsuarioCreo) {
        this.idUsuarioCreo = idUsuarioCreo;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Integer getIdModificaCrea() {
        return this.idModificaCrea;
    }
    
    public void setIdModificaCrea(Integer idModificaCrea) {
        this.idModificaCrea = idModificaCrea;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getTblUsuarioSociedads() {
        return this.tblUsuarioSociedads;
    }
    
    public void setTblUsuarioSociedads(Set tblUsuarioSociedads) {
        this.tblUsuarioSociedads = tblUsuarioSociedads;
    }
    public Set getTblUsuarioPerfils() {
        return this.tblUsuarioPerfils;
    }
    
    public void setTblUsuarioPerfils(Set tblUsuarioPerfils) {
        this.tblUsuarioPerfils = tblUsuarioPerfils;
    }




}


