package modelo.pojo;
// Generated 15-mar-2017 16:17:44 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblUsuarioSociedad generated by hbm2java
 */
public class TblUsuarioSociedad  implements java.io.Serializable {


     private int id;
     private TblSociedad tblSociedad;
     private TblUsuario tblUsuario;
     private Boolean estado;
     private Integer idUsuarioCreo;
     private Date fechaCreacion;
     private Integer idModificaCrea;
     private Date fechaModificacion;

    public TblUsuarioSociedad() {
    }

	
    public TblUsuarioSociedad(int id) {
        this.id = id;
    }
    public TblUsuarioSociedad(int id, TblSociedad tblSociedad, TblUsuario tblUsuario, Boolean estado, Integer idUsuarioCreo, Date fechaCreacion, Integer idModificaCrea, Date fechaModificacion) {
       this.id = id;
       this.tblSociedad = tblSociedad;
       this.tblUsuario = tblUsuario;
       this.estado = estado;
       this.idUsuarioCreo = idUsuarioCreo;
       this.fechaCreacion = fechaCreacion;
       this.idModificaCrea = idModificaCrea;
       this.fechaModificacion = fechaModificacion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public TblSociedad getTblSociedad() {
        return this.tblSociedad;
    }
    
    public void setTblSociedad(TblSociedad tblSociedad) {
        this.tblSociedad = tblSociedad;
    }
    public TblUsuario getTblUsuario() {
        return this.tblUsuario;
    }
    
    public void setTblUsuario(TblUsuario tblUsuario) {
        this.tblUsuario = tblUsuario;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Integer getIdUsuarioCreo() {
        return this.idUsuarioCreo;
    }
    
    public void setIdUsuarioCreo(Integer idUsuarioCreo) {
        this.idUsuarioCreo = idUsuarioCreo;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Integer getIdModificaCrea() {
        return this.idModificaCrea;
    }
    
    public void setIdModificaCrea(Integer idModificaCrea) {
        this.idModificaCrea = idModificaCrea;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


